export const modelConfig = {
  flux: {
    name: "Flux.1 Schnell",
    category: "General",
    group: "Base Models",
    huggingfaceId: "black-forest-labs/FLUX.1-schnell",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: null,
    tagline: "Balanced of speed and quality",
    image: "https://i.ibb.co.com/51P0fS0/out-0.webp",
    example: "the prompt should be clear, should describe the users base prompt in best way and add extra elements to it for maximizing performance, you can add word tags that might enhance the image result or effect its styles",
    steps: 4,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false
  },
  turbo: {
    name: "SD-3.5Large-turbo",
    category: "General",
    group: "Base Models",
    huggingfaceId: "stabilityai/stable-diffusion-3.5-large-turbo",
    qualityLimits: ["HD"],
    isPremium: false,
    promptSuffix: null,
    tagline: "Fastest generation with good quality",
    image: "https://i.ibb.co.com/3C2N2LJ/1734417062623.jpg",
    example: "the prompt should be clear, should describe the users base prompt in best way and add extra elements to it for maximizing performance, you can add word tags that might enhance the image result or effect its styles",
    steps: 4,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  sd35l: {
    name: "SD-3.5Large",
    category: "General",
    group: "Base Models",
    huggingfaceId: "stabilityai/stable-diffusion-3.5-large",
    qualityLimits: ["HD"],
    isPremium: false,
    promptSuffix: null,
    tagline: "Latest Stable diffusion model",
    image: "https://i.ibb.co/XDLVk6m/R8-sd3-5-L-00001.webp",
    example: "the prompt should be clear, should describe the users base prompt in best way and add extra elements to it for maximizing performance, you can add word tags that might enhance the image result or effect its styles",
    steps: 40,
    use_guidance: true,
    defaultguidance: 4.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  fluxDev: {
    name: "FLx.1 Dev",
    category: "General",
    group: "Base Models",
    huggingfaceId: "black-forest-labs/FLUX.1-dev",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: null,
    tagline: "Flux dev by black forest labs",
    image: "https://i.ibb.co/gjrM8R5/out-0-1.webp",
    example: "the prompt should be clear, should describe the users base prompt in best way and add extra elements to it for maximizing performance, you can add word tags that might enhance the image result or effect its styles",
    steps: 28,
    use_guidance: false,
    use_negative_prompt: false
  },
  ultra: {
    name: "Flux.1 Pro",
    category: "General",
    group: "Base Models",
    huggingfaceId: "strangerzonehf/Flux-Ultimate-LoRA-Collection",
    qualityLimits: null,
    isPremium: true,
    promptSuffix: null,
    tagline: "A merge of multiple models",
    image: "https://i.ibb.co/Tqb5Pgk/sample.jpg",
    example: "the prompt should be clear, should describe the users base prompt in best way and add extra elements to it for maximizing performance, you can add word tags that might enhance the image result or effect its styles",
    steps: 30,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  midjourney: {
    name: "Midjourney-V6",
    category: "General",
    group: "Style Models",
    huggingfaceId: "strangerzonehf/Flux-Midjourney-Mix2-LoRA",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", MJ v6",
    tagline: "Latest version of Midjourney for free",
    image: "https://i.ibb.co/8PnDLkf/1.png",
    example: "Start with 'MJ v6,'. Make high quality flawless prompts that will go well wth Midjourney, the prompt should be clear, should describe the users base prompt in best way and add extra elements to it for maximizing performance, you can add word tags that might enhance the image result or effect its styles",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  midjourney2: {
    name: "Midjourney-V6 Variant",
    category: "General",
    group: "Style Models",
    huggingfaceId: "Jovie/Midjourney",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: " ``",
    tagline: "Latest version of Midjourney for free",
    image: "https://i.ibb.co/4pfMnCH/images-example-wbu24jq33.jpg",
    example: "Make high quality flawless prompts that will go well wth Midjourney, the prompt should be clear, should describe the users base prompt in best way and add extra elements to it for maximizing performance, you can add word tags that might enhance the image result or effect its styles",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  logodesign: {
    name: "Logo Design",
    category: "General",
    group: "Logo Maker",
    huggingfaceId: "Shakker-Labs/FLUX.1-dev-LoRA-Logo-Design",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", wablogo, logo, Minimalist",
    tagline: "Best for making Emblem logos",
    image: "https://i.ibb.co/277njvK/03.png",
    example: "Start with 'wablogo, logo, Minimalist' Then describe the logo to appear in the image, Describe a proper emblem for the logo from color to appearance and shape describe precisely the best use case is asking the logo to be a fusion of 2 known icons or symbols merged too look like what user might want the logo to be, if given information than state whats the logo for it maximizes performance",
    steps: 28,
    use_guidance: false,
    defaultguidance: 5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  logodesign2: {
    name: "Logo Design 2",
    category: "General",
    group: "Logo Maker",
    huggingfaceId: "imagepipeline/Logo",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: null,
    tagline: "If you are not sure about what you want",
    image: "https://i.ibb.co/H4cRCjY/458ae986-877f-4928-997e-e80349b4fc13.jpg",
    example: "Start with 'Logo' Then describe the logo to appear in the image, describe whats the logo for too if given information about that, be super minimal, if given information than state whats the logo for it maximizes performance",
    steps: 28,
    use_guidance: false,
    defaultguidance: 5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  logodesign3: {
    name: "Logo Design 3",
    category: "General",
    group: "Logo Maker",
    huggingfaceId: "brianling16/logo-lora",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: null,
    tagline: "If your idea lacks creativity then this is for you",
    image: "https://i.ibb.co.com/7dF5kfrw/image.png",
    example: "Start with 'Logo' Then describe the logo to appear in the image, if given information than state whats the logo for it maximizes performance",
    steps: 28,
    use_guidance: false,
    defaultguidance: 5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  logodesign4: {
    name: "Logo Design 4",
    category: "General",
    group: "Logo Maker",
    huggingfaceId: "prithivMLmods/Logo-Design-Flux-LoRA",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: null,
    tagline: "Super precise and absolute",
    image: "https://i.ibb.co/VTP3NLz/LD2.png",
    example: "Start with 'Logo' Then describe the logo to appear in the image, be precise and creative, is user base prompt lacks any idea about the logo add your own idea suitable for that, you can focus on logos that mix text and emblem together",
    steps: 28,
    use_guidance: false,
    defaultguidance: 5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  dalle: {
    name: "Dall-E 3",
    category: "General",
    group: "Base Models",
    huggingfaceId: "Nercy/flux-dalle",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", dalle",
    tagline: "Open AI Dall-E 3",
    image: "https://i.ibb.co.com/18gFNNS/images-example-kz79mj1mz.jpg",
    example: "the prompt should be clear, should describe the users base prompt in best way and add extra elements to it for maximizing performance, you can add word tags that might enhance the image result or effect its styles",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  realism: {
    name: "Realism",
    category: "General",
    group: "Style Models",
    huggingfaceId: "imagepipeline/Flux_Realism_Super_Lora",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", photography, photorealistic",
    tagline: "make realistic images fast",
    image: "https://i.ibb.co/hWtLp3S/ip-realism.png",
    example: "Start with 'A photorealistic portrait of' .Make high quality flawless prompt, use quality and style tags like: high quality, studio lighting, professional portrait. make it not too long not too short, provide fine details like environment, lighting, colors, visual elements, if included charachters then styling, clothings, appearance, activity e.t.c",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
    fantasy: {
    name: "Fantasy",
    category: "General",
    group: "Style Models",
    huggingfaceId: "Shakker-Labs/FLUX.1-dev-LoRA-Dark-Fantasy",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: null,
    tagline: "Make Dark fantsy images",
    image: "https://i.ibb.co/Tqs8PQD/c2215bd73da9f14fcd63cc93350e66e2901bdafa6fb8abaaa2c32a1b.jpg",
    example: "tailer prompt to make fantasy images and use a few unnecessary tags from this: heavily influenced by Klee, Odilon Redon, Eyvind Earle, Roberto Venosa, Sidney Simes, Jan Toorop cinematic still, forced perspective 3/4 angle, bird's eye viewpoint, looking down at main character, dynamic pose of elegant ethereal female Archangel, extraordinarily detailed wings crystalline velvety wings wrapped around her, graceful contrapost chiasm, chiaroscuro, stylised masterpiece award-winning, luscious colour palette, perfect colour grading, perfect balance between lineart, colour, light and volume, delicate, sophisticated, exquisite, Cinematic, Photography, Shot on 70mm, Depth of Field, F/5.6, soft shadows, 8K, genius, award-winning , rim lighting, polygonal statue, VRay tracing style, greek goddess, pop art illustration, etruscan art, fragment icon, neoclassicism, future technology, white textured greek god sculpture, young woman, beauty, coated sunglasses, glowing gold jewelry, greek robe, full body shot, angel wings, serious expression, surrealism, primary color high quality white, background color pure glowing high quality yellow, realistic graphics, photo-realistic, ultra-detailed, fantasy style, 32k",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  render3d: {
    name: "3D Render XL",
    category: "General",
    group: "3D",
    huggingfaceId: "goofyai/3D_Render_for_Flux",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", 3D render",
    tagline: "render 3D images",
    image: "https://i.ibb.co/sbmM5mp/3d-style-2.jpg",
    example: "Start with 'a 3D rendered scene of'. Make high quality flawless prompt, use quality and style tags like: high quality, studio lighting, 3D style, blender style, 3D rendered. make it not too long not too short, provide fine details like environment, lighting, colors, visual elements, if included charachters then styling, clothings, appearance, activity e.t.c. End with ', blender style'",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  anime: {
    name: "Anime",
    category: "General",
    group: "Anime",
    huggingfaceId: "Nishitbaria/Anime-style-flux-lora-Large",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", anm",
    tagline: "Flwaless Anime style images",
    image: "https://i.ibb.co/c1kPmWg/Euv-INv-Bs-CKZQusp-ZHN-u-F.png",
    example: "make sure the prompt excels in making Anime style images, add any word tags that might enhance or indicate to Anime styles.",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  anime2xl: {
    name: "Anime 2",
    category: "General",
    group: "Anime",
    huggingfaceId: "imagepipeline/flux-Anime",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", animexl",
    tagline: "Anime style images make fast",
    image: "https://i.ibb.co/hc3dWxr/images-example-zgfn69jth.jpg",
    example: "make sure the prompt excels in making Anime style images, add any word tags that might enhance or indicate to Anime styles.",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  animexl: {
    name: "Anime Xl",
    category: "General",
    group: "Anime",
    huggingfaceId: "Jovie/Anime",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: " ``",
    tagline: "Anime XL, Unreal Anime style images",
    image: "https://i.ibb.co.com/zWmjSkcy/image.png",
    example: "make sure the prompt excels in making Anime style images, add any word tags that might enhance or indicate to Anime styles.",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  ghiblianime: {
    name: "Ghibli Anime",
    category: "General",
    group: "Anime",
    huggingfaceId: "aleksa-codes/flux-ghibsky-illustration",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", GHIBSKY style painting",
    tagline: "Modern Anime style images make",
    image: "https://i.ibb.co/x6r9FVK/example7.jpg",
    example: "make sure the prompt excels in making studio ghibli Anime style images, add any word tags that might enhance or indicate to ghibli Anime styles.",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  dreamscape: {
    name: "Dreamscape",
    category: "General",
    group: "Style Models",
    huggingfaceId: "bingbangboom/flux_dreamscape",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", in the style of BSstyle004",
    tagline: "Dream up",
    image: "https://i.ibb.co/nkxPsYG/images-2.jpg",
    example: "Start with 'in the style of BSstyle004,'. follow this example: 'white-haired young man, extremely simple, large-scale blue, brightly colored board, dark white and light blue' always craft the user given prompt in this example format while ensuring what user wnats is reflected",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  cinestill: {
    name: "CineStill",
    category: "General",
    group: "Style Models",
    huggingfaceId: "adirik/flux-cinestill",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", CNSTLL",
    tagline: "make distilled Cinematic scenes",
    image: "https://i.ibb.co/rs5g7Xz/3.png",
    example: "Start with 'CNSTLL,'. Best suited for generating night and dusk time photograph-like images with a distinctive slight halation effect. Keywords that result in better generations 'cinestill 800t', 'night time', 'dusk', '4k', 'high resolution', 'analog film'. Example: 'in the style of CNSTLL , urban landscape, people fishing on Galata  bridge in Istanbul at night'",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  asianbeauty: {
    name: "Asian Beauty",
    category: "General",
    group: "Style Models",
    huggingfaceId: "TDN-M/East-asian-beauty",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: null,
    tagline: "Asian beauty adorned in realism",
    image: "https://i.ibb.co/ZWYt9Vz/ea2.webp",
    example: "make prompts for asian beauty images",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  shouXin: {
    name: "Shou Xin",
    category: "General",
    group: "Art",
    huggingfaceId: "hassanelmghari/shou_xin",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", shou_xin, pencil sketch",
    tagline: "sketch art pencil and colors",
    image: "https://i.ibb.co/P4xLs4W/img-00282.png",
    example: "Start with 'shou_xin A color pencil sketch of' then describe a minimal sketch image subject and End with ', close up, minimalist, impressionism, negative space' heres an example: 'shou_xin, a monochromatic pencil sketch of a crow, minimalist, impressionism, negative space', heres another example: 'shou_xin, A pencil sketch of steve jobs, minimalist, impressionism, negative space'",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  Illustration: {
    name: "Illustration Art",
    category: "General",
    group: "Art",
    huggingfaceId: "lichorosario/flux-lora-simple-vector",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", v3ct0r, vector",
    tagline: "Create Vector arts",
    image: "https://i.ibb.co/wKszPV2/images-example-ylmvpzdqk.jpg",
    example: "Start with 'v3ct0r style, simple flat vector art, isolated on white bg,' Then describe the Vector Graphics element that should show in the image. Heres an example: 'v3ct0r style, simple flat vector art, isolated on white bg, rocket' heres another example: 'v3ct0r style, simple flat vector art, isolated on white bg, kawaii bread slice wearing black frame eyeglasses. Small smile. There is a blue flower pink center placed at the top right corner of the bread slice.'",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  Isometric: {
    name: "Isometric",
    category: "General",
    group: "3D",
    huggingfaceId: "strangerzonehf/Flux-Isometric-3D-LoRA",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", Isometric 3D",
    tagline: "Isometric style, build your world",
    image: "https://i.ibb.co/88P57s7/ID2.png",
    example: "Start with 'Isometric 3D, a 3D model of' Then describe the things to appear in the image, heres an example: 'Isometric 3D, a 3D model of a tropical island is displayed on a light blue backdrop. The island features a small body of water, surrounded by gray rocks and green grass. There are palm trees and small bushes scattered throughout the island, adding a pop of color to the scene.'",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  mixreality: {
    name: "Mix Reality",
    category: "General",
    group: "Style Models",
    huggingfaceId: "Shakker-Labs/FLUX.1-dev-LoRA-Logo-Design",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: null,
    tagline: "When cartoon charachters cross over too real-world",
    image: "https://i.ibb.co/gw2DNvN/images-3.jpg",
    example: "Make prompt for making images where reality and anime or illustration mixes, example: 'A vivid photo of a 2D illustrated anime girl riding a bicycle, busy street, road signs. The photo is a blend of illustration and reality, in the style of HLFILSTHLFPHTO'",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  fashion: {
    name: "Fashion Photography",
    category: "General",
    group: "Style Models",
    huggingfaceId: "imagepipeline/Fashion",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: null,
    tagline: "Create Fashion Models",
    image: "https://i.ibb.co/n8SLF9M/1d7def8c-d9a7-47c3-aabd-4e1a718aad89.jpg",
    example: "Make prompt for making images of Fashion photography, example: 'A fashion model in a red dress, standing in front of a white background. The model has long brown hair and is wearing a red dress with a plunging neckline. The dress has a fitted bodice and a full skirt. The model is wearing red lipstick and has her hair styled in loose waves. She is looking directly at the camera with a serious expression.'",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  sticker: {
    name: "Sticker",
    category: "General",
    group: "Art",
    huggingfaceId: "prithivMLmods/Ton618-Only-Stickers-Flux-LoRA",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", Only Sticker",
    tagline: "Make your brand Identity",
    image: "https://i.ibb.co/Ryx6b4B/111.png",
    example: "Start with 'Only Sticker, An animated image of a' Then describe the sticker to appear in the image, heres an example: 'Only Sticker, An animated illustration of a sloth in a mug with the words 'Sloth Fuel' written on it. The sloth is holding the mug with its left hand and its right hand resting on the mug. The mug is filled with coffee and there is a brown liquid dripping from the bottom of the cup. There is a white background behind the sloth with a smoke coming out of it. There are three coffee beans on the bottom left corner of the image.'",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  handwriting: {
    name: "Handwriting",
    category: "General",
    group: "Art",
    huggingfaceId: "fofr/flux-handwriting",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", HWRIT handwriting",
    tagline: "Real lookin handwriting images",
    image: "https://i.ibb.co/mFPgMkj/0041358a-ee46-4cab-85f5-108c4f09b729.jpg",
    example: "make prompt like this: HWRIT very neat handwriting saying 'this is a handwriting model'(replace this with the text to write in the image), black(replace with suitable color) ink on white_paper(replace with on what to write)",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  teenoutfitGenerator: {
    name: "Teen Outfit",
    category: "General",
    group: "Design",
    huggingfaceId: "prithivMLmods/Teen-Outfit",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", Teen Outfit",
    tagline: "Make cool outfits and cloths",
    image: "https://i.ibb.co/MCWQZBN/TO3.png",
    example: "Start with 'Teen Outfit,' Then describe the outfit in very details, then dream of the outfit to appear in the image, based on users base prompt and add extra elements to it for maximizing performance, you can add word tags that might enhance the image result or effect its styles",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  pixelArt: {
    name: "Pixel Art",
    category: "General",
    group: "Art",
    huggingfaceId: "mindlywork/pixel_art_style_v1.0",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", pixel_art_style_v1.0",
    tagline: "Modern Pixel art",
    image: "https://i.ibb.co/DkdtLrG/Comfy-UI-00047.png",
    example: "Tailor prompt to make Pixel art images and start with 'pixel_art_style_v1.0'",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  iconkit: {
    name: "Icon Kit",
    category: "General",
    group: "Design",
    huggingfaceId: "strangerzonehf/Flux-Icon-Kit-LoRA",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", Icon kit",
    tagline: "3d Icons",
    image: "https://i.ibb.co/cxqCCnf/1-1.png",
    example: "Start with 'Icon Kit, An animated image of' then describe a minimal element as icon for the image and at the end describe a suitable calm background color, heres an example: 'Icon Kit, An animated image of a red canister with a black cap on the top. The canister has a black stripe on the side and a yellow hose attached to the cap. The background is a bright blue color.'",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  gameassets: {
    name: "Game assets",
    category: "General",
    group: "Design",
    huggingfaceId: "gokaygokay/Flux-Game-Assets-LoRA-v2",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", wbgmsst",
    tagline: "Create game assets",
    image: "https://i.ibb.co/vdMRPnn/images-example-c6ery92u6.jpg",
    example: "Start with 'wbgmsst', Tailor prompt to make Game assets images with white background, make sure the prompt excels in making game assets images, add any word tags that might enhance or indicate to game assets styles.",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },


  // NSFW Models
  nsfwMaster: {
    name: "Real",
    category: "NSFW",
    group: "NSFW",
    huggingfaceId: "xey/sldr_flux_nsfw_v2-studio",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: ", Nsfw, naked,",
    tagline: "NSFW generation",
    image: "https://i.ibb.co/qm9ZjV4/b36e71ed-c142-49c4-8ba5-4f3a57bd6ae9.jpg",
    example: "craft high quality prompts to make images of naked girls in nudity related things",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  animeNsfw: {
    name: "Anime",
    category: "NSFW",
    group: "NSFW",
    huggingfaceId: "Niggendar/malaAnimeMixNSFW_v50",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: null,
    tagline: "Anime-style NSFW generation",
    image: "https://axrooawblvsspndfmvan.supabase.co/storage/v1/object/public/user-images/b574a759-4898-4bd4-8624-5e984407217e/1733812329671.png?width=1024&quality=75&format=webp",
    example: "craft high quality prompts to make images of naked girls in nudity or sex related things",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  },
  deepthroat: {
    name: "Deep throated",
    category: "NSFW",
    group: "NSFW",
    huggingfaceId: "pimpilikipilapi1/bj",
    qualityLimits: null,
    isPremium: false,
    promptSuffix: " deepthroat, sucking, blowjob",
    tagline: "Anime-style NSFW generation",
    image: "https://i.ibb.co.com/XZ45xfQV/814cd1e9-5c39-48e9-bc65-43cbe3b39e70.jpg",
    example: "craft high quality prompts to make images of naked girls in nudity or sex related things",
    steps: 28,
    use_guidance: false,
    defaultguidance: 7.5,
    use_negative_prompt: false,
    default_negative_prompt: "ugly, bad anatomy, blurry, pixelated, poor quality, watermark, signature, text"
  }
};
