// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcngfvuiqtynqhfrvoit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjbmdmdnVpcXR5bnFoZnJ2b2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzNTgxNTUsImV4cCI6MjA1MDkzNDE1NX0.MQ4iAxv9zho1Rt629tSoQCUnnGmXU3uaMDWB66fkCzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);